include: package:flutter_lints/flutter.yaml
linter: 
  rules: 
    use_build_context_synchronously: false
    always_use_package_imports: true
analyzer:
  errors:
    always_use_package_imports: error
